'use client';
import Head from 'next/head';

import { NorthAmerica } from '@/components/NorthAmerica/NorthAmerica';
import { Oceania } from '@/components/Oceania/Oceania';
import { Europe } from '@/components/Europe/Europe';

import { SouthAmerica } from '@components/SouthAmerica/SouthAmerica';
import { Asia } from '@/components/Asia/Asia';
import { Header } from '@/components/Header/Header';
import { GlobalDistribution } from '@/components/GlobalDistribution/GlobalDistribution';

import styles from '@/styles/Home.module.scss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
        <GlobalDistribution />
        <NorthAmerica />
        <SouthAmerica />
        <Oceania />
        <Europe />
        <Asia />
      </main>
    </>
  );
}
